name: tk1
version: 16-0.1
summary: Nvidia TK1
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image for the Nvidia TK1.
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: make
    source: git://git.denx.de/u-boot.git
    artifacts: [u-boot.img]
    prepare: |
      make apalis-tk1_defconfig
    build: |
      CROSS_COMPILE=arm-linux-gnueabi- make
    install: |
      cp u-boot.img $SNAPCRAFT_PART_INSTALL/
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env
      cd $SNAPCRAFT_PART_INSTALL/; ln -s uboot.env uboot.conf
    build-packages:
      - libpython2.7-dev
      - build-essential
      - bc
      - gcc-arm-linux-gnueabi
